### ISSUE TITLE
Use Server's PostgreSQL to replace container PostgreSQL 

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/ansible-awx#10]
1. replace PostgreSQL container and enable phpPgAdmin
2. refer to: http://support.websoft9.com/docs/awx/solution-more.html#use-an-external-postgresql-with-ssl-mode

**Comment by qiaofeng1227** [comment]
ok

**Comment by qiaofeng1227** [comment]
Password init need delete all the tables of awx database in PostgreSQL

**Comment by chendelin1982** [comment]
After test, I found that docker.service and postgresql.service will conflict when they as Befor items in the  int-apps.service file
