### ISSUE TITLE
redis container not running

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/ansible-awx#11]
docker logs awx_redis
```
1:C 09 Dec 2020 08:14:45.892 # Configuration loaded
1:M 09 Dec 2020 08:14:45.900 # Opening Unix socket: bind: No such file or directory
1:C 09 Dec 2020 08:14:52.867 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 09 Dec 2020 08:14:52.867 # Redis version=6.0.9, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 09 Dec 2020 08:14:52.867 # Configuration loaded
1:M 09 Dec 2020 08:14:52.868 # Opening Unix socket: bind: No such file or directory
```

**Comment by qiaofeng1227** [comment]
AWX compose file use [official Redis Docker image](https://registry.hub.docker.com/_/redis), if delete personalized redis.conf in it, Redis container is running

**Comment by Hmengchao** [comment]
1:C 15 Dec 2020 03:21:55.645 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 15 Dec 2020 03:21:55.657 # Redis version=6.0.9, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 15 Dec 2020 03:21:55.657 # Configuration loaded
1:M 15 Dec 2020 03:21:55.658 # Opening Unix socket: bind: Address already in use

**Comment by qiaofeng1227** [comment]
Done
