### ISSUE TITLE
已经通过AWX安装了环境的受控主机，一旦更换系统后，第二次AWX就连不上了

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/ansible-awx#2]
修改配置文件“~/.ssh/config”，加上这两行，重启服务器。
StrictHostKeyChecking no
UserKnownHostsFile /dev/null

**Comment by hliblack** [comment]
修改 /var/lib/awx/.ssh  目录内配置config文件 内容为 
StrictHostKeyChecking no
UserKnownHostsFile /dev/null

**Comment by chendelin1982** [comment]
/var/lib/awx/.ssh/known_hosts
