### ISSUE TITLE
[BUG] Loses all configurations when someone restarts the environment

### ISSUE THREAD

**Issue by OnlyHardOfficial** [Websoft9/ansible-awx#30]
Suposes i have all my repositoryes and all credentials configured, all my machines ans etc ..
everything is already well configured!
For some reason I need to restart the machine, all of a sudden erases all my settings, hosts, passwords, erases everything.
The environment is basically reseted as in the image below
![image](https://user-images.githubusercontent.com/19652056/134997441-7c9627e9-bc8b-42ae-a158-c3d813aab551.png)

### Bug Context
Im Using your latest version here:
$ wget -N https://raw.githubusercontent.com/Websoft9/ansible-linux/main/scripts/install.sh; bash install.sh -r awx

1 - Instalation with sucess on enviroment - Ubuntu20.04LTS
2 - Configure all configs | Clone repos - Fully Working - All ok
3 - All working fine - OK
4 - For some reason, i need to restart my machine - I lose everything - (FAIL HERE WITH SUCESS)
5 - We need to fix this issue

## Bug source

- [X] Bugs from installation 

## System Environment
**SO**
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal
**ANSIBLE VERSION**
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/onlyhard/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Jun  2 2021, 10:49:15) [GCC 9.4.0]

My ANSIBLE config:
https://pastebin.com/9i1t4MHJ

**OS**
- [x] Ubuntu20.x

**Your solution for Bug**

You can describe your solution here

**Additional context**

You can add any other context about the problem here.

**Comment by chendelin1982** [comment]
Hello, it our bug. When you first install AWX, it should restart Server because we have init script to init AWS first time.
I want to know, the second Restart operation, is there aslo clear all data?

**Comment by OnlyHardOfficial** [comment]
> is there aslo clear all data?

Yes, clear all the data.

**Comment by chendelin1982** [comment]
This reason is that we have add init script for the first restart. When complete this installation, it should reboot automaticly (force), but some problem caused no restart on your server.

We have fix it, thank you
