### ISSUE TITLE
/usr/local/bin/ansible-playbook路径错误，我的在/usr/bin/

### ISSUE THREAD

**Issue by wangmt2000** [Websoft9/ansible-awx#7]
TASK [awx : Run the AWX installation playbook.] *************************************************************************************************************************************
fatal: [192.168.239.128]: FAILED! => {"changed": true, "cmd": "/usr/local/bin/ansible-playbook -i inventory install.yml -e ansible_python_interpreter=/usr/bin/python3 -e postgres_data_dir=~/.awx/pgdocker -e docker_compose_dir=~/.awx/awxcompose", "delta": "0:00:00.004309", "end": "2020-04-11 12:52:01.119917", "msg": "non-zero return code", "rc": 127, "start": "2020-04-11 12:52:01.115608", "stderr": "/bin/sh: /usr/local/bin/ansible-playbook: 没有那个文件或目录", "stderr_lines": ["/bin/sh: /usr/local/bin/ansible-playbook: 没有那个文件或目录"], "stdout": "", "stdout_lines": []}

**Comment by chendelin1982** [comment]
Fixed it
